Make sure to catch NoClassDefFoundError when trying to query the framework classloader for whether a class is available or not. Previously, it was possible that this query was leaked to bundles because of the error propagate all the way to the bundle that instigated the classload.
git-svn-id: https://svn.apache.org/repos/asf/felix/trunk@644939 13f79535-47bb-0310-9956-ffa450edef68